### PR TITLE
Fix build on node 0.12.7

### PR DESCRIPTION
**Pull request by Rush**
I had errors like:
```
 CXX(target) Release/obj.target/libvirt/src/worker.o
  CXX(target) Release/obj.target/libvirt/src/interface.o
  CXX(target) Release/obj.target/libvirt/src/network.o
  CXX(target) Release/obj.target/libvirt/src/network_filter.o
  CXX(target) Release/obj.target/libvirt/src/node_device.o
  CXX(target) Release/obj.target/libvirt/src/secret.o
  CXX(target) Release/obj.target/libvirt/src/storage_pool.o
  CXX(target) Release/obj.target/libvirt/src/storage_volume.o
  CXX(target) Release/obj.target/libvirt/src/domain.o
../src/domain.cc: In static member function ‘static void NodeLibvirt::Domain::SetSchedulerParameters(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/domain.cc:2002:48: error: call of overloaded ‘NanThrowError(v8::Local<v8::Object>)’ is ambiguous
     NanThrowError(Error::New(virGetLastError()));
                                                ^
../src/domain.cc:2002:48: note: candidates are:
In file included from ../src/error.h:5:0,
                 from ../src/domain.cc:3:
../node_modules/nan/nan.h:705:21: note: void NanThrowError(v8::Handle<v8::String>)
     NAN_INLINE void NanThrow ## NAME(v8::Handle<v8::String> errmsg) {          \
                     ^
../node_modules/nan/nan.h:711:3: note: in expansion of macro ‘X’
   X(Error)
   ^
../node_modules/nan/nan.h:719:19: note: void NanThrowError(v8::Handle<v8::Value>)
   NAN_INLINE void NanThrowError(v8::Handle<v8::Value> error) {
                   ^
../src/domain.cc:2017:48: error: call of overloaded ‘NanThrowError(v8::Local<v8::Object>)’ is ambiguous
     NanThrowError(Error::New(virGetLastError()));
                                                ^
../src/domain.cc:2017:48: note: candidates are:
In file included from ../src/error.h:5:0,
                 from ../src/domain.cc:3:
../node_modules/nan/nan.h:705:21: note: void NanThrowError(v8::Handle<v8::String>)
     NAN_INLINE void NanThrow ## NAME(v8::Handle<v8::String> errmsg) {          \
                     ^
../node_modules/nan/nan.h:711:3: note: in expansion of macro ‘X’
   X(Error)
   ^
../node_modules/nan/nan.h:719:19: note: void NanThrowError(v8::Handle<v8::Value>)
   NAN_INLINE void NanThrowError(v8::Handle<v8::Value> error) {
                   ^
../src/domain.cc:2054:48: error: call of overloaded ‘NanThrowError(v8::Local<v8::Object>)’ is ambiguous
     NanThrowError(Error::New(virGetLastError()));
                                                ^
../src/domain.cc:2054:48: note: candidates are:
In file included from ../src/error.h:5:0,
                 from ../src/domain.cc:3:
../node_modules/nan/nan.h:705:21: note: void NanThrowError(v8::Handle<v8::String>)
     NAN_INLINE void NanThrow ## NAME(v8::Handle<v8::String> errmsg) {          \
                     ^
../node_modules/nan/nan.h:711:3: note: in expansion of macro ‘X’
   X(Error)
   ^
../node_modules/nan/nan.h:719:19: note: void NanThrowError(v8::Handle<v8::Value>)
   NAN_INLINE void NanThrowError(v8::Handle<v8::Value> error) {
                   ^
make: *** [Release/obj.target/libvirt/src/domain.o] Error 1
```

This pull request fixes it.

### CODE REVIEW

**Comment by c4milo** [comment]
LGTM. I will let @mbroadst to have the final word.

**Comment by dariusc93** [comment]
I do get this same error when compiling and this does fixes it but i feel that something is off with it.

**Comment by Rush** [comment]
What is off? I think somebody fixed v8 so that exceptions can be anything, hence `Value` and not `Object`.

**Comment by dariusc93** [comment]
Might explain why broke when it was working just fine last week for me.

**Comment by mbroadst** [comment]
There was definitely an effort to move most uses of v8::Object handles with v8::Value since they are should generally be the same. So this looks good to me, but reading through nan's 2.0.0 release, it looks like we need to do another pass switching most of our code to use the "Nan" namespace.

On another note, I'll try to see if I can find some time tomorrow to enable travis just for building the module to ensure that we at least can guarantee that with different versions of node. Currently running the tests in travis is a no-go since the test driver seems to maintain some state, leading to tests failing if run in a certain order (I would _love_ someone for life if they wanted to play around with fixing this as I have very little time atm :smile:)

**Comment by dariusc93** [comment]
@mbroadst is there any chance of updating npm registry or are you holding off for now?

**Comment by mbroadst** [comment]
@dariusc93 I'd like to get some form of Travis builds working, as well as investigate updating to nan 2.0.0 before publishing, in order to reduce future churn. I'll have a better answer by the end of the weekend

**Comment by dariusc93** [comment]
Okay thanks!
